#! /bin/bash
echo "How many Fabonacci numbers do you want to display? "
declare -i TOTAL
read TOTAL
echo "Here are "$TOTAL" Fabonacci numbers:"

declare -i A
declare -i B
declare -i C
A=1
B=1
echo $A
echo $B
TOTAL=$TOTAL-2

for i in $(seq $TOTAL)
do
    C=$A+$B
    echo $C
    A=$B
    B=$C
done

exit 0
